/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Servis ve veri tazeliği durumu
         * @description Uptime kontrolü ve son senkron durumu. Veri bayatsa `status` `degraded` olur;
         *     servis yine de çalışmaya devam eder.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * İlçe listesi ve ilçe başına nöbetçi sayısı
         * @description Konum izni reddedildiğinde gösterilen ilçe seçim ekranını besler.
         *     Nöbetçi sayısı o an nöbette olan eczaneleri sayar.
         */
        get: operations["listDistricts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pharmacies/on-duty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nöbetçi eczaneler
         * @description İki kullanım biçimi vardır ve **tam olarak biri** seçilmelidir:
         *
         *     - **Konuma göre:** `lat` + `lng` verilir. Sonuç mesafeye göre artan sıralanır,
         *       her kayıtta `distanceM` ve `etaMin` bulunur.
         *     - **İlçeye göre:** `district` verilir. Sonuç eczane adına göre sıralanır,
         *       `distanceM` ve `etaMin` `null` olur.
         *
         *     `etaMin` haversine mesafesinden türetilmiş **tahmindir**; gerçek trafik verisi
         *     içermez. Gerekçe: `docs/adr/002-harita-yol-tarifi.md`
         *
         *     Nöbeti bitmiş eczaneler varsayılan olarak dönmez; `includeExpired=true` ile
         *     `status: "closed"` şeklinde döner (tasarımdaki soluk satırlar).
         *
         *     **İl konumdan çözülür.** `lat`/`lng` verilip `city` verilmezse sunucu en yakın
         *     eczanenin ilini seçer; hangi ili seçtiği yanıtın `cityCode` alanındadır.
         *     Kullanıcı ili elle değiştirdiğinde `city` gönderilir ve konumdan çözüm yapılmaz.
         *
         *     Veri o il için henüz çekilmemişse `items` boş ve `stale` `true` döner —
         *     **hata değildir**, arayüz boş durum ekranını gösterir.
         */
        get: operations["listOnDutyPharmacies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Yönetici girişi
         * @description Başarılı girişte `HttpOnly; Secure; SameSite=Strict` oturum çerezi kurulur.
         *     Kimlik bilgileri kodda değil, ortam değişkenlerinden gelir; parola PBKDF2 ile
         *     hash'lenmiş saklanır. Karşılaştırma sabit zamanlıdır.
         */
        post: operations["adminLogin"];
        /** Oturumu kapat */
        delete: operations["adminLogout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Desteklenen il listesi
         * @description Çekim komutu il argümanını (plaka kodu ya da slug) buradan çözer.
         *     `districtCount` 0 ise o il için henüz hiç veri çekilmemiş demektir.
         */
        get: operations["listCities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/known-coords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Koordinatı zaten bilinen eczane slug'ları
         * @description Çekim komutu bunu kullanarak **gereksiz harita isteği yapmaz** (ADR-005).
         *     Verilen slug'lardan hangilerinin lat/lng'si dolu, onu döner.
         */
        get: operations["listKnownCoords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Çekilen nöbet listesini topluca yaz
         * @description Tek çağrıda: bilinmeyen ilçeleri ekler, eczaneleri slug'a göre upsert eder,
         *     o güne ait nöbetleri yazar.
         *
         *     **Elle girilmiş koordinat korunur:** `coordSource = 'manual'` olan eczanenin
         *     lat/lng'si bu uçtan ASLA ezilmez (ADR-005).
         *
         *     O gün için daha önce yazılmış `source='edevlet'` nöbetleri silinip yeniden
         *     yazılır — böylece kaynaktan çıkarılan bir eczane bizde asılı kalmaz.
         *     `source='manual'` nöbetlere dokunulmaz.
         *
         *     `edevlet` değeri kaynağın adı DEĞİL, "otomatik çekim" kovasının adıdır;
         *     elle girilenden ayırır. Gerekçe: `docs/adr/007-eczaneler-gen-tr-kaynagi.md`
         */
        post: operations["importDuties"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/scrape/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Çekimi elle tetikle
         * @description Çekim Cloudflare'in **dışında** koşar (GitHub Actions). Bu uç yalnızca
         *     `repository_dispatch` çağrısı yapar — tek subrequest, HTML ayrıştırma yok.
         *     Gerekçe: ücretsiz planda invocation başına 10 ms CPU / 50 dış subrequest
         *     sınırı 81 ilin ayrıştırmasına yetmez (ADR-006).
         *
         *     Kaynağa saygı gereği **10 dakikada bir** tetiklenebilir; daha sık denemede
         *     `429` döner. Sonuç anında gelmez: iş akışı birkaç dakika sonra
         *     `POST /api/admin/scrape/runs` ile koşu kayıtlarını yazar.
         */
        post: operations["triggerScrape"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/scrape/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Son çekim koşuları
         * @description Panelin çekim sekmesi bunu gösterir: hangi il, hangi gün, ne sonuç verdi.
         *     En yeni koşu başta döner.
         */
        get: operations["listScrapeRuns"];
        put?: never;
        /**
         * Bir çekim koşusunun sonucunu yaz
         * @description Çekim komutu her il-gün bitiminde bunu çağırır. Kayıt **tamamlanmış** koşuyu
         *     anlatır; `outcome` alanı ne olduğunu söyler. Sessiz bozulma buradan görülür:
         *     `rowsFound` düşerse ya da `error` birikirse kaynak değişmiş demektir.
         */
        post: operations["recordScrapeRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Oturum geçerli mi
         * @description Panel açılışında oturumun hâlâ geçerli olduğunu doğrulamak için.
         */
        get: operations["getAdminMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/pharmacies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Eczane kayıtları
         * @description Panelin eczane defteri. Nöbet ataması ayrı bir kayıttır (`/api/admin/duties`);
         *     buradaki liste eczanenin kendisidir, nöbette olup olmadığından bağımsızdır.
         *
         *     Veri 81 ili kapsadığı için liste **her zaman sayfalıdır**: `total` toplam
         *     eşleşmeyi, `items` bu sayfayı verir.
         */
        get: operations["listAdminPharmacies"];
        put?: never;
        /** Eczane ekle */
        post: operations["createPharmacy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/pharmacies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Eczane sil
         * @description Eczaneye bağlı nöbet kayıtları da silinir.
         */
        delete: operations["deletePharmacy"];
        options?: never;
        head?: never;
        /** Eczane güncelle */
        patch: operations["updatePharmacy"];
        trace?: never;
    };
    "/api/admin/duties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nöbet atamaları
         * @description Takvimde bir güne tıklandığında açılan liste. 81 ilde bir günün nöbeti
         *     binlerce satır olabildiği için sonuç **sayfalıdır** ve pratikte il
         *     filtresiyle kullanılır.
         */
        get: operations["listDuties"];
        put?: never;
        /**
         * Nöbet ata
         * @description Nöbet penceresi `date` gününün 08:00 TRT'sinden ertesi gün 08:00 TRT'sine kadardır.
         *     Aynı eczaneye aynı gün için ikinci atama yapılamaz.
         */
        post: operations["createDuty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/duties/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aylık nöbet takvimi
         * @description Panelin takvim ızgarasını besler: ayın her günü için nöbet sayısı ve
         *     kaynağa göre dağılım. **Eksik gün buradan görülür** — sayısı 0 olan gün
         *     ızgarada işaretlenir.
         *
         *     Yalnızca kayıt bulunan günler döner; boş günler dizide yer almaz.
         */
        get: operations["getDutyCalendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/duties/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Nöbet atamasını kaldır */
        delete: operations["deleteDuty"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @enum {string} */
                code: "bad_request" | "unauthorized" | "not_found" | "city_not_supported" | "rate_limited" | "source_unavailable" | "dispatch_failed" | "not_configured" | "internal";
                /** @description Kullanıcıya gösterilebilir Türkçe mesaj. */
                message: string;
                /** @description Alan bazlı doğrulama hataları. */
                details?: {
                    path: string;
                    message: string;
                }[];
            };
        };
        Health: {
            /**
             * @description Bugünün verisi yoksa `degraded`.
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** @example 0.1.0 */
            version: string;
            /**
             * Format: date-time
             * @description Son **başarılı** senkron zamanı.
             */
            lastSyncAt: string | null;
            /** @description Servis edilen veri bugünün rotasyonuna ait değil. */
            stale: boolean;
        };
        District: {
            /** @example 0715 */
            code: string;
            /** @example Muratpaşa */
            name: string;
            /** @example 6 */
            onDutyCount: number;
        };
        DistrictList: {
            /** @example 7 */
            cityCode: number;
            stale: boolean;
            /** Format: date-time */
            dataAsOf: string | null;
            items: components["schemas"]["District"][];
        };
        Pharmacy: {
            /**
             * @description `{sourceKey}:{sourceId}` — kaynaklar arası çakışmayan kalıcı kimlik.
             * @example antalya-eo:8680001234567
             */
            id: string;
            /** @example Deniz Eczanesi */
            name: string;
            /**
             * @description E.164 formatında. `tel:` bağlantısında doğrudan kullanılır.
             * @example +902422371414
             */
            phone: string | null;
            address: string;
            districtCode: string;
            districtName: string;
            /** @description Koordinat kaynaktan ayrı bir istekle geliyor; henüz bilinmiyor olabilir. */
            lat: number | null;
            /** Format: double */
            lng: number | null;
            /** @description Kuş uçuşu mesafe (metre). İlçeye göre sorguda `null`. */
            distanceM: number | null;
            /**
             * @description **Tahmini** sürüş süresi (dakika). Mesafeden türetilir, trafik içermez.
             *     Arayüzde `~` ile gösterilir. İlçeye göre sorguda `null`.
             */
            etaMin: number | null;
            /** Format: date-time */
            dutyStart: string;
            /** Format: date-time */
            dutyEnd: string;
            /**
             * @description `closing_soon`: kapanışa 120 dakikadan az kaldı — tasarımda turuncu varyant.
             *     `closed`: nöbet bitti — yalnızca `includeExpired=true` ile döner.
             * @enum {string}
             */
            status: "open" | "closing_soon" | "closed";
            /** @description Nöbetin bitmesine kalan dakika. Bitmişse negatif. */
            minutesUntilClose: number;
        };
        PharmacyList: {
            /**
             * @description `true` ise veri bugünün rotasyonuna ait değil. Arayüz çevrimdışı/kayıtlı
             *     bilgi bandını gösterir ve birincil aksiyonu "Ara" yapar.
             */
            stale: boolean;
            /**
             * Format: date-time
             * @description Veriyi kaynaktan çeken son başarılı senkronun zamanı.
             */
            dataAsOf: string | null;
            /**
             * Format: date-time
             * @description Nöbetin döneceği bir sonraki an (her gün 08:00 TRT).
             */
            nextRotationAt: string;
            /** @example 7 */
            cityCode: number;
            items: components["schemas"]["Pharmacy"][];
        };
        City: {
            /** @example 7 */
            code: number;
            /** @example Antalya */
            name: string;
            /** @example antalya */
            slug: string;
            districtCount: number;
        };
        ImportItem: {
            /** @example antalya/akseki/murtici */
            slug: string;
            name: string;
            districtName: string;
            districtSlug: string;
            address: string;
            phone: string | null;
            /** Format: date-time */
            dutyStart: string;
            /** Format: date-time */
            dutyEnd: string;
            lat: number | null;
            lng: number | null;
            /** @description Kaynaktaki "Durumu" sütunu, ham hâliyle. */
            sourceStatus?: string | null;
        };
        ImportRequest: {
            cityCode: number;
            dutyDate: string;
            /** @enum {string} */
            source: "edevlet";
            items: components["schemas"]["ImportItem"][];
        };
        ImportResult: {
            districtsCreated: number;
            pharmaciesCreated: number;
            pharmaciesUpdated: number;
            dutiesWritten: number;
            /** @description Kaynaktan çıkarıldığı için silinen önceki edevlet nöbetleri. */
            dutiesRemoved: number;
            /** @description Elle girildiği için korunan koordinat sayısı. */
            coordsPreserved: number;
        };
        /** @description Eczane oluşturma ve güncelleme gövdesi. PATCH'te de tüm alanlar zorunludur. */
        PharmacyInput: {
            /** @example Deniz Eczanesi */
            name: string;
            /**
             * @description Serbest biçimde girilebilir; sunucu E.164'e normalize eder.
             * @example 0242 237 14 14
             */
            phone: string | null;
            address: string;
            /** @example 0715 */
            districtCode: string;
            /** Format: double */
            lat: number | null;
            /** Format: double */
            lng: number | null;
            /** @description Yalnızca panelde görünür. Genel API'de dönmez. */
            notes?: string | null;
        };
        AdminPharmacy: {
            id: number;
            /**
             * @description Doğal anahtar: il/ilçe/eczane. Bkz. ADR-005.
             * @example antalya/akseki/murtici
             */
            slug: string;
            name: string;
            phone: string | null;
            address: string;
            districtCode: string;
            districtName: string;
            /** Format: double */
            lat: number | null;
            /** Format: double */
            lng: number | null;
            /**
             * @description `manual` ise çekim bu koordinatı ASLA ezmez.
             * @enum {string}
             */
            coordSource: "edevlet" | "manual";
            notes: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        DutyInput: {
            pharmacyId: number;
            /**
             * @description Nöbetin başladığı gün (TRT). Pencere: o gün 08:00 → ertesi gün 08:00.
             * @example 2026-08-08
             */
            date: string;
        };
        CalendarDay: {
            /** @example 2026-08-08 */
            date: string;
            count: number;
            /** @description Çekimden gelen nöbet sayısı. */
            edevletCount: number;
            /** @description Panelden elle eklenen nöbet sayısı. */
            manualCount: number;
        };
        ScrapeTriggerInput: {
            /**
             * @description `tum` → 81 il. Tek il için plaka kodunu metin olarak ver (`"7"`).
             * @default tum
             */
            scope: string;
            /**
             * @default ikisi
             * @enum {string}
             */
            days: "bugun" | "yarin" | "ikisi";
        };
        ScrapeTriggerResult: {
            /** Format: date-time */
            dispatchedAt: string;
            scope: string;
            /** @enum {string} */
            days: "bugun" | "yarin" | "ikisi";
        };
        ScrapeRunInput: {
            cityCode: number;
            dutyDate: string;
            /**
             * Format: date-time
             * @description Milisaniyesiz UTC: `YYYY-MM-DDTHH:MM:SSZ` (CLAUDE.md kota kuralı).
             */
            startedAt: string;
            /** @enum {string} */
            outcome: "ok" | "partial" | "error";
            /** @default 0 */
            rowsFound: number;
            /** @default 0 */
            pharmaciesNew: number;
            /** @default 0 */
            dutiesWritten: number;
            /**
             * @description Bu koşuda kaynağa atılan harita isteği sayısı.
             * @default 0
             */
            coordsFetched: number;
            /** @default 0 */
            rowsSkipped: number;
            errorMessage?: string | null;
        };
        ScrapeRun: {
            id: number;
            cityCode: number;
            /** @example Antalya */
            cityName: string;
            /** @example 2026-08-08 */
            dutyDate: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt: string | null;
            /** @enum {string} */
            outcome: "ok" | "partial" | "error";
            rowsFound: number;
            pharmaciesNew: number;
            dutiesWritten: number;
            coordsFetched: number;
            rowsSkipped: number;
            errorMessage: string | null;
        };
        DutyShift: {
            id: number;
            pharmacyId: number;
            pharmacyName: string;
            districtCode: string;
            districtName: string;
            /** @example 2026-08-08 */
            date: string;
            /** Format: date-time */
            dutyStart: string;
            /** Format: date-time */
            dutyEnd: string;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: {
        /** @description Geçersiz istek parametresi */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Oturum yok veya geçersiz */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Kayıt bulunamadı */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Çok fazla deneme */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description Plaka kodu (81 ilin tamamı). `lat`/`lng` verildiğinde **gerekmez**: sunucu
         *     ili konumdan çözer ve hangi ili seçtiğini yanıttaki `cityCode` ile bildirir.
         *     Konum yoksa varsayılan 7 (Antalya).
         */
        CityCode: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Servis ayakta */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listDistricts: {
        parameters: {
            query?: {
                /**
                 * @description Plaka kodu (81 ilin tamamı). `lat`/`lng` verildiğinde **gerekmez**: sunucu
                 *     ili konumdan çözer ve hangi ili seçtiğini yanıttaki `cityCode` ile bildirir.
                 *     Konum yoksa varsayılan 7 (Antalya).
                 */
                city?: components["parameters"]["CityCode"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description İlçe listesi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistrictList"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listOnDutyPharmacies: {
        parameters: {
            query?: {
                /**
                 * @description Kullanıcı enlemi. `lng` ile birlikte verilir, `district` ile birlikte verilemez.
                 * @example 36.8969
                 */
                lat?: number;
                /**
                 * @description Kullanıcı boylamı. `lat` ile birlikte verilir, `district` ile birlikte verilemez.
                 * @example 30.7133
                 */
                lng?: number;
                /**
                 * @description TÜİK ilçe kodu. `lat`/`lng` ile birlikte verilemez.
                 * @example 0715
                 */
                district?: string;
                /**
                 * @description Plaka kodu (81 ilin tamamı). `lat`/`lng` verildiğinde **gerekmez**: sunucu
                 *     ili konumdan çözer ve hangi ili seçtiğini yanıttaki `cityCode` ile bildirir.
                 *     Konum yoksa varsayılan 7 (Antalya).
                 */
                city?: components["parameters"]["CityCode"];
                /** @description Döndürülecek azami kayıt sayısı. */
                limit?: number;
                /** @description Nöbeti bitmiş eczaneleri de döndür. */
                includeExpired?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nöbetçi eczane listesi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PharmacyList"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    adminLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Giriş başarılı, oturum çerezi kuruldu */
            204: {
                headers: {
                    /** @example session=…; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=28800 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            /** @description Kimlik bilgileri hatalı */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    adminLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Oturum kapatıldı */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description İl listesi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["City"][];
                    };
                };
            };
        };
    };
    listKnownCoords: {
        parameters: {
            query: {
                city: number;
                /** @description Virgülle ayrılmış slug listesi. */
                slugs: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Koordinatı bilinen slug'lar */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        slugs: string[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    importDuties: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Yazıldı */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description İl desteklenmiyor */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    triggerScrape: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Alanların hepsi varsayılanlı; boş gövde `{}` gönderilebilir. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScrapeTriggerInput"];
            };
        };
        responses: {
            /** @description İş akışı tetiklendi */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "dispatchedAt": "2026-08-08T11:12:03Z",
                     *       "scope": "tum",
                     *       "days": "ikisi"
                     *     }
                     */
                    "application/json": components["schemas"]["ScrapeTriggerResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            /** @description GitHub'a ulaşılamadı veya dispatch reddedildi */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Tetikleme yapılandırılmamış (`GITHUB_DISPATCH_TOKEN` / `GITHUB_REPO` yok) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listScrapeRuns: {
        parameters: {
            query?: {
                /** @description Plaka kodu. Verilmezse tüm iller. */
                city?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Koşu listesi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ScrapeRun"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    recordScrapeRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScrapeRunInput"];
            };
        };
        responses: {
            /** @description Koşu kaydedildi */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapeRun"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getAdminMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Oturum geçerli */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        username: string;
                        /** Format: date-time */
                        expiresAt: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listAdminPharmacies: {
        parameters: {
            query?: {
                /** @description Ad veya adres içinde arama. */
                q?: string;
                /** @description Plaka kodu. Verilmezse tüm iller. */
                city?: number;
                district?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eczane listesi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total: number;
                        items: components["schemas"]["AdminPharmacy"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createPharmacy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PharmacyInput"];
            };
        };
        responses: {
            /** @description Oluşturuldu */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPharmacy"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Aynı ad ve ilçede kayıt zaten var */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deletePharmacy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Silindi */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updatePharmacy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PharmacyInput"];
            };
        };
        responses: {
            /** @description Güncellendi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPharmacy"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listDuties: {
        parameters: {
            query?: {
                /** @description Nöbet günü (YYYY-MM-DD, TRT). Verilmezse bugün. */
                date?: string;
                /** @description Plaka kodu. Verilmezse tüm iller. */
                city?: number;
                district?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O güne ait nöbet atamaları */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        date: string;
                        /** @description Filtreye uyan toplam kayıt. */
                        total: number;
                        items: components["schemas"]["DutyShift"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createDuty: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DutyInput"];
            };
        };
        responses: {
            /** @description Atandı */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DutyShift"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Bu eczane o gün için zaten nöbetçi */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getDutyCalendar: {
        parameters: {
            query: {
                /**
                 * @description Ay (YYYY-MM, TRT takvimi).
                 * @example 2026-08
                 */
                month: string;
                /** @description Plaka kodu. Verilmezse tüm iller. */
                city?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gün başına nöbet sayıları */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "month": "2026-08",
                     *       "cityCode": 7,
                     *       "days": [
                     *         {
                     *           "date": "2026-08-08",
                     *           "count": 37,
                     *           "edevletCount": 37,
                     *           "manualCount": 0
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        /** @example 2026-08 */
                        month: string;
                        cityCode: number | null;
                        days: components["schemas"]["CalendarDay"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteDuty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Silindi */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
